const Ddata = [
  {
    cover: "./discount/discount-1.png",
    name: "BenuX 2022",
    price: "Rs 250",
    offer: "20%",
    Shop: "Shop: ACS",
  },
  {
    cover: "./discount/discount-2.png",
    name: "Sony TV",
    price: "Rs 450",
    offer: "50%",
    Shop: "Shop: ACS",
  },
  {
    cover: "./discount/discount-3.png",
    name: "Sony PS4",
    price: "Rs 50",
    offer: "15%",
    Shop: "Shop: ACS",
  },
  {
    cover: "./discount/discount-4.png",
    name: "Setgearr",
    price: "Rs 100",
    offer: "10%",
    Shop: "Shop: ACS",
  },
  {
    cover: "./discount/discount-5.png",
    name: "Tony BGB",
    price: "Rs 20",
    offer: "45%",
    Shop: "Shop: ACS",
  },
  {
    cover: "./discount/discount-6.png",
    name: "RG products",
    price: "Rs 200",
    offer: "25%",
    Shop: "Shop: ACS",
  },
  {
    cover: "./discount/discount-7.png",
    name: "Ranasonic",
    price: "Rs 300",
    offer: "30%",
    Shop: "Shop: ACS",
  },
  {
    cover: "./discount/discount-8.png",
    name: "Pune HD",
    price: "Rs 30",
    offer: "20%",
    Shop: "Shop: ACS",
  },
  {
    cover: "./discount/discount-9.png",
    name: "Sony CCTV",
    price: "Rs 80",
    offer: "30%",
    Shop: "Shop: ACS",
  },
];
export default Ddata;
